global using AutoMapper;
global using FluentValidation;
global using MediatR;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
global using System.ComponentModel.DataAnnotations;
global using System.Text.Json.Serialization;
global using Talabat.Application.Account.DTOs;
global using Talabat.Application.Order.DTOs;
global using Talabat.Application.Products.DTOs;
global using Talabat.Application.Reviews.DTOs;
global using Talabat.Application.Wishlist.DTOs;
global using Talabat.Domain.Shared.Exceptions;
global using Talabat.Domain.Models;
global using Talabat.Domain.Repositories;
global using Talabat.Domain.Services;
global using Talabat.Domain.Shared;
global using Talabat.Domain.Shared.Constants;
global using Talabat.Domain.Shared.Params;
global using Talabat.Domain.Shared.Payment;
global using Talabat.Domain.Specifications.EntitiesSpecifications;
global using static Talabat.Application.Order.DTOs.OrderDto;
global using static Talabat.Application.Products.DTOs.ProductDto;
global using static Talabat.Application.Wishlist.DTOs.WishListItemDto;
global using UserOrder = Talabat.Domain.Models.Order;
